language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
xcode_project: SwiftFormValidator.xcodeproj
xcode_scheme: SwiftFormValidator

before_install:
  - gem install cocoapods -v '1.2.0'

script:
  - xcodebuild clean build test -project SwiftFormValidator.xcodeproj -scheme SwiftFormValidator -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6"
  - pod lib lint
