language: objective-c
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1
xcode_project: SwiftFormValidator.xcodeproj
xcode_scheme: SwiftFormValidator

before_install:
  - gem install cocoapods -v '1.2.0'
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild clean build test -project SwiftFormValidator.xcodeproj -scheme SwiftFormValidator -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.1,name=iPhone 6" CODE_SIGNING_REQUIRED=NO | xcpretty
  - pod lib lint
